### PR TITLE
MicroPython: getting rid of warnings during compilation MicroPython tests

### PR DESCRIPTION
**Pull request by PNieck**
## Description

This PR contains small adjustments in MicroPython tests.It gets rid of warnings during compilation of `test_micropython.c` file.

## Motivation and Context

More elegant code.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `ia32-generic-qemu`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by damianloew — APPROVED** [review]
LGTM

**Comment by nalajcie** [comment]
please fix the commit message (it's unnecessarily longer than 78 chars), maybe just `micropython: fix compilation warnings` or something similar (please use imperative mood)

**Comment by PNieck** [comment]
> please fix the commit message (it's unnecessarily longer than 78 chars), maybe just `micropython: fix compilation warnings` or something similar (please use imperative mood)

Done

**Review by nalajcie — APPROVED** [review]
Tanks for fixing compilation warnings.

**Comment by damianloew** [comment]
> Tanks for fixing compilation warnings.

Yeah, but I've asked for adding a related task from JIRA

**Review by damianloew — APPROVED** [review]
Thanks for mentioning a task from JIRA in commit message, everything seems to be fine now.

**Pull request merged**
