### PR TITLE
trunner: armv7a7-imx6ull: Increase jffs2 command timeout

### PR DESCRIPTION
**Pull request by maska989**
## Description

Changed timeout for jffs2 command based on phoenix size after nightly build (~16MB) and MT25QL256 documentation (max 1s/64KB erase)

## Motivation and Context
Our boards are equipped with MT25QL256 NOR 
From manufacturer documentation, we can decode the size of it (32Mb) 

Screenshot from 2023-09-25 11-42-32
 
Manufacturer inform users about `Sector erase time` (This time is given for 64kb of data) 

Screenshot from 2023-09-25 11-39-57
that means in the worst scenario, it will erase 512 seconds(8.5 minutes).
We divided this value in half and add time which is needed for setting up clean markers, because nightly campaign right now weight exactly half of its space.
Screenshot from 2023-09-22 08-48-02

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [X] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [X] Tested by hand on: armv7a7-imx6ull-evk.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing linter checks and tests passed.
- [X] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by damianloew — CHANGES_REQUESTED** [review]
Thanks for this change!

Maybe:

Changed timeout for jffs2 command based on phoenix size after nightly build (~16MB) and MT25QL256 documentation (max 1s/64KB erase)

and

trunner: armv7a7-imx6ull: Increase jffs2 command timeout

(we rather want to have short commit messages)

**Comment by nalajcie** [comment]
@badochov can you confirm the logic behind the computations is ok?

**Comment by badochov** [comment]
> @badochov can you confirm the logic behind the computations is ok?

seems fine to me

**Review by damianloew — APPROVED** [review]
LGTM

**Pull request merged**
