### PR TITLE
libc: add exit, _exit, atexit tests

### PR DESCRIPTION
**Pull request by adamdebek**
JIRA: CI-209

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by adamdebek** [comment]
Need submodule update to pass.

**Review by damianloew — COMMENTED** [review]
Please update this PR. Moreover, the following commit can be removed, yes?
`libc: add exit, _exit, atexit tests`

**Comment by damianloew** [comment]
Why closed?

**Comment by adamdebek** [comment]
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/287

**Pull request closed without merging**
