### PR TITLE
psh: enable test execution in new psh for imxrt117x

### PR DESCRIPTION
**Pull request by mateusz-bloch**
JIRA: CI-461

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by damianloew — COMMENTED** [review]
Please add an info in commit description that it's done due to resolving #866 issue

**Review by damianloew — COMMENTED** [review]
`It is enable due to resolved of the issue` - that's not gramatically correct, it should be rather:
`It is enabled due to the following issue resolution: ...`

**Review by damianloew — COMMENTED** [review]
Have you tested that on current changes it works stable?

**Comment by mateusz-bloch** [comment]
> Have you tested that on current changes it works stable?

So the issue, reported in phoenix-rtos/phoenix-rtos-project#1103, still exists. To run the tests with changes, we can either disable the test or possibly try running it first. I tested with a reboot before the test, but the issue still occurs.

**Review by damianloew — APPROVED** [review]

**Pull request merged**
